package com.modern.www._1_2_MySql_DB_entities;
// Generated May 13, 2022 7:18:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ambulance generated by hbm2java
 */
@Entity
@Table(name="ambulance"
    ,catalog="smrtamb"
)
public class Ambulance  implements java.io.Serializable {


     private int carNumber;
     private String address;
     private Set<AmbulanceSupplies> ambulanceSupplieses = new HashSet<AmbulanceSupplies>(0);
     private Set<PatientAmbulanceHospital> patientAmbulanceHospitals = new HashSet<PatientAmbulanceHospital>(0);

    public Ambulance() {
    }

	
    public Ambulance(int carNumber, String address) {
        this.carNumber = carNumber;
        this.address = address;
    }
    public Ambulance(int carNumber, String address, Set<AmbulanceSupplies> ambulanceSupplieses, Set<PatientAmbulanceHospital> patientAmbulanceHospitals) {
       this.carNumber = carNumber;
       this.address = address;
       this.ambulanceSupplieses = ambulanceSupplieses;
       this.patientAmbulanceHospitals = patientAmbulanceHospitals;
    }
   
     @Id 

    
    @Column(name="car_number", unique=true, nullable=false)
    public int getCarNumber() {
        return this.carNumber;
    }
    
    public void setCarNumber(int carNumber) {
        this.carNumber = carNumber;
    }

    
    @Column(name="address", nullable=false, length=150)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="ambulance")
    public Set<AmbulanceSupplies> getAmbulanceSupplieses() {
        return this.ambulanceSupplieses;
    }
    
    public void setAmbulanceSupplieses(Set<AmbulanceSupplies> ambulanceSupplieses) {
        this.ambulanceSupplieses = ambulanceSupplieses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="ambulance")
    public Set<PatientAmbulanceHospital> getPatientAmbulanceHospitals() {
        return this.patientAmbulanceHospitals;
    }
    
    public void setPatientAmbulanceHospitals(Set<PatientAmbulanceHospital> patientAmbulanceHospitals) {
        this.patientAmbulanceHospitals = patientAmbulanceHospitals;
    }




}


