package com.modern.www._1_2_MySql_DB_entities;
// Generated May 13, 2022 7:18:24 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CaseSupplies generated by hbm2java
 */
@Entity
@Table(name="case_supplies"
    ,catalog="smrtamb"
)
public class CaseSupplies  implements java.io.Serializable {


     private CaseSuppliesId id;
     private CaseData caseData;
     private Supplies supplies;
     private String stretcherType;

    public CaseSupplies() {
    }

    public CaseSupplies(CaseSuppliesId id, CaseData caseData, Supplies supplies, String stretcherType) {
       this.id = id;
       this.caseData = caseData;
       this.supplies = supplies;
       this.stretcherType = stretcherType;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="caseId", column=@Column(name="case_id", nullable=false) ), 
        @AttributeOverride(name="supplyId", column=@Column(name="supply_id", nullable=false) ) } )
    public CaseSuppliesId getId() {
        return this.id;
    }
    
    public void setId(CaseSuppliesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="case_id", nullable=false, insertable=false, updatable=false)
    public CaseData getCaseData() {
        return this.caseData;
    }
    
    public void setCaseData(CaseData caseData) {
        this.caseData = caseData;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="supply_id", nullable=false, insertable=false, updatable=false)
    public Supplies getSupplies() {
        return this.supplies;
    }
    
    public void setSupplies(Supplies supplies) {
        this.supplies = supplies;
    }

    
    @Column(name="stretcher_type", nullable=false, length=150)
    public String getStretcherType() {
        return this.stretcherType;
    }
    
    public void setStretcherType(String stretcherType) {
        this.stretcherType = stretcherType;
    }




}


