package com.modern.www._1_2_MySql_DB_entities;
// Generated May 13, 2022 7:18:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CaseData generated by hbm2java
 */
@Entity
@Table(name="case_data"
    ,catalog="smrtamb"
)
public class CaseData  implements java.io.Serializable {


     private int caseId;
     private String caseName;
     private Set<CaseSupplies> caseSupplieses = new HashSet<CaseSupplies>(0);
     private Set<PatientCase> patientCases = new HashSet<PatientCase>(0);

    public CaseData() {
    }

	
    public CaseData(int caseId, String caseName) {
        this.caseId = caseId;
        this.caseName = caseName;
    }
    public CaseData(int caseId, String caseName, Set<CaseSupplies> caseSupplieses, Set<PatientCase> patientCases) {
       this.caseId = caseId;
       this.caseName = caseName;
       this.caseSupplieses = caseSupplieses;
       this.patientCases = patientCases;
    }
   
     @Id 

    
    @Column(name="case_id", unique=true, nullable=false)
    public int getCaseId() {
        return this.caseId;
    }
    
    public void setCaseId(int caseId) {
        this.caseId = caseId;
    }

    
    @Column(name="case_name", nullable=false, length=150)
    public String getCaseName() {
        return this.caseName;
    }
    
    public void setCaseName(String caseName) {
        this.caseName = caseName;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="caseData")
    public Set<CaseSupplies> getCaseSupplieses() {
        return this.caseSupplieses;
    }
    
    public void setCaseSupplieses(Set<CaseSupplies> caseSupplieses) {
        this.caseSupplieses = caseSupplieses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="caseData")
    public Set<PatientCase> getPatientCases() {
        return this.patientCases;
    }
    
    public void setPatientCases(Set<PatientCase> patientCases) {
        this.patientCases = patientCases;
    }




}


