package com.modern.www._1_2_MySql_DB_entities;
// Generated May 13, 2022 7:18:24 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CaseSuppliesId generated by hbm2java
 */
@Embeddable
public class CaseSuppliesId  implements java.io.Serializable {


     private int caseId;
     private int supplyId;

    public CaseSuppliesId() {
    }

    public CaseSuppliesId(int caseId, int supplyId) {
       this.caseId = caseId;
       this.supplyId = supplyId;
    }
   


    @Column(name="case_id", nullable=false)
    public int getCaseId() {
        return this.caseId;
    }
    
    public void setCaseId(int caseId) {
        this.caseId = caseId;
    }


    @Column(name="supply_id", nullable=false)
    public int getSupplyId() {
        return this.supplyId;
    }
    
    public void setSupplyId(int supplyId) {
        this.supplyId = supplyId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CaseSuppliesId) ) return false;
		 CaseSuppliesId castOther = ( CaseSuppliesId ) other; 
         
		 return (this.getCaseId()==castOther.getCaseId())
 && (this.getSupplyId()==castOther.getSupplyId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCaseId();
         result = 37 * result + this.getSupplyId();
         return result;
   }   


}


