package com.modern.www._1_2_MySql_DB_entities;
// Generated May 13, 2022 7:18:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChronicDisease generated by hbm2java
 */
@Entity
@Table(name="chronic_disease"
    ,catalog="smrtamb"
)
public class ChronicDisease  implements java.io.Serializable {


     private int diseaseId;
     private String diseaseName;
     private Set<PatientDiseases> patientDiseaseses = new HashSet<PatientDiseases>(0);

    public ChronicDisease() {
    }

	
    public ChronicDisease(int diseaseId, String diseaseName) {
        this.diseaseId = diseaseId;
        this.diseaseName = diseaseName;
    }
    public ChronicDisease(int diseaseId, String diseaseName, Set<PatientDiseases> patientDiseaseses) {
       this.diseaseId = diseaseId;
       this.diseaseName = diseaseName;
       this.patientDiseaseses = patientDiseaseses;
    }
   
     @Id 

    
    @Column(name="disease_id", unique=true, nullable=false)
    public int getDiseaseId() {
        return this.diseaseId;
    }
    
    public void setDiseaseId(int diseaseId) {
        this.diseaseId = diseaseId;
    }

    
    @Column(name="disease_name", nullable=false, length=150)
    public String getDiseaseName() {
        return this.diseaseName;
    }
    
    public void setDiseaseName(String diseaseName) {
        this.diseaseName = diseaseName;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="chronicDisease")
    public Set<PatientDiseases> getPatientDiseaseses() {
        return this.patientDiseaseses;
    }
    
    public void setPatientDiseaseses(Set<PatientDiseases> patientDiseaseses) {
        this.patientDiseaseses = patientDiseaseses;
    }




}


