package com.modern.www._1_2_MySql_DB_entities;
// Generated May 13, 2022 7:18:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name="department"
    ,catalog="smrtamb"
)
public class Department  implements java.io.Serializable {


     private int departmentNumber;
     private String departmentName;
     private Set<Hospital> hospitals = new HashSet<Hospital>(0);
     private Set<Doctor> doctors = new HashSet<Doctor>(0);

    public Department() {
    }

	
    public Department(int departmentNumber, String departmentName) {
        this.departmentNumber = departmentNumber;
        this.departmentName = departmentName;
    }
    public Department(int departmentNumber, String departmentName, Set<Hospital> hospitals, Set<Doctor> doctors) {
       this.departmentNumber = departmentNumber;
       this.departmentName = departmentName;
       this.hospitals = hospitals;
       this.doctors = doctors;
    }
   
     @Id 

    
    @Column(name="department_number", unique=true, nullable=false)
    public int getDepartmentNumber() {
        return this.departmentNumber;
    }
    
    public void setDepartmentNumber(int departmentNumber) {
        this.departmentNumber = departmentNumber;
    }

    
    @Column(name="department_name", nullable=false, length=100)
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

@ManyToMany(fetch=FetchType.EAGER, mappedBy="departments")
    public Set<Hospital> getHospitals() {
        return this.hospitals;
    }
    
    public void setHospitals(Set<Hospital> hospitals) {
        this.hospitals = hospitals;
    }

@ManyToMany(fetch=FetchType.EAGER, mappedBy="departments")
    public Set<Doctor> getDoctors() {
        return this.doctors;
    }
    
    public void setDoctors(Set<Doctor> doctors) {
        this.doctors = doctors;
    }




}


