package com.modern.www._1_2_MySql_DB_entities;
// Generated May 13, 2022 7:18:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name="doctor"
    ,catalog="smrtamb"
)
public class Doctor  implements java.io.Serializable {


     private long ssn;
     private Hospital hospital;
     private String name;
     private String spatialize;
     private Set<PatientSurgeryDoctor> patientSurgeryDoctors = new HashSet<PatientSurgeryDoctor>(0);
     private Set<Department> departments = new HashSet<Department>(0);

    public Doctor() {
    }

	
    public Doctor(long ssn, Hospital hospital, String name, String spatialize) {
        this.ssn = ssn;
        this.hospital = hospital;
        this.name = name;
        this.spatialize = spatialize;
    }
    public Doctor(long ssn, Hospital hospital, String name, String spatialize, Set<PatientSurgeryDoctor> patientSurgeryDoctors, Set<Department> departments) {
       this.ssn = ssn;
       this.hospital = hospital;
       this.name = name;
       this.spatialize = spatialize;
       this.patientSurgeryDoctors = patientSurgeryDoctors;
       this.departments = departments;
    }
   
     @Id 

    
    @Column(name="SSN", unique=true, nullable=false)
    public long getSsn() {
        return this.ssn;
    }
    
    public void setSsn(long ssn) {
        this.ssn = ssn;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="hospital_id", nullable=false)
    public Hospital getHospital() {
        return this.hospital;
    }
    
    public void setHospital(Hospital hospital) {
        this.hospital = hospital;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="spatialize_", nullable=false, length=150)
    public String getSpatialize() {
        return this.spatialize;
    }
    
    public void setSpatialize(String spatialize) {
        this.spatialize = spatialize;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="doctor")
    public Set<PatientSurgeryDoctor> getPatientSurgeryDoctors() {
        return this.patientSurgeryDoctors;
    }
    
    public void setPatientSurgeryDoctors(Set<PatientSurgeryDoctor> patientSurgeryDoctors) {
        this.patientSurgeryDoctors = patientSurgeryDoctors;
    }

@ManyToMany(fetch=FetchType.EAGER)
    @JoinTable(name="doctor_department", catalog="smrtamb", joinColumns = { 
        @JoinColumn(name="SSN", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="department_number", nullable=false, updatable=false) })
    public Set<Department> getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Set<Department> departments) {
        this.departments = departments;
    }




}


