package com.modern.www._1_2_MySql_DB_entities;
// Generated May 13, 2022 7:18:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PatientCaseId generated by hbm2java
 */
@Embeddable
public class PatientCaseId  implements java.io.Serializable {


     private Date transDate;
     private long ssn;
     private int caseId;

    public PatientCaseId() {
    }

    public PatientCaseId(Date transDate, long ssn, int caseId) {
       this.transDate = transDate;
       this.ssn = ssn;
       this.caseId = caseId;
    }
   


    @Column(name="trans_date", nullable=false, length=10)
    public Date getTransDate() {
        return this.transDate;
    }
    
    public void setTransDate(Date transDate) {
        this.transDate = transDate;
    }


    @Column(name="SSN", nullable=false)
    public long getSsn() {
        return this.ssn;
    }
    
    public void setSsn(long ssn) {
        this.ssn = ssn;
    }


    @Column(name="case_id", nullable=false)
    public int getCaseId() {
        return this.caseId;
    }
    
    public void setCaseId(int caseId) {
        this.caseId = caseId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PatientCaseId) ) return false;
		 PatientCaseId castOther = ( PatientCaseId ) other; 
         
		 return ( (this.getTransDate()==castOther.getTransDate()) || ( this.getTransDate()!=null && castOther.getTransDate()!=null && this.getTransDate().equals(castOther.getTransDate()) ) )
 && (this.getSsn()==castOther.getSsn())
 && (this.getCaseId()==castOther.getCaseId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTransDate() == null ? 0 : this.getTransDate().hashCode() );
         result = 37 * result + (int) this.getSsn();
         result = 37 * result + this.getCaseId();
         return result;
   }   


}


