package com.modern.www._1_2_MySql_DB_entities;
// Generated May 13, 2022 7:18:24 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PatientDiseases generated by hbm2java
 */
@Entity
@Table(name="patient_diseases"
    ,catalog="smrtamb"
)
public class PatientDiseases  implements java.io.Serializable {


     private PatientDiseasesId id;
     private ChronicDisease chronicDisease;
     private Patient patient;
     private String treatment;

    public PatientDiseases() {
    }

    public PatientDiseases(PatientDiseasesId id, ChronicDisease chronicDisease, Patient patient, String treatment) {
       this.id = id;
       this.chronicDisease = chronicDisease;
       this.patient = patient;
       this.treatment = treatment;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="ssn", column=@Column(name="SSN", nullable=false) ), 
        @AttributeOverride(name="diseaseId", column=@Column(name="disease_id", nullable=false) ) } )
    public PatientDiseasesId getId() {
        return this.id;
    }
    
    public void setId(PatientDiseasesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="disease_id", nullable=false, insertable=false, updatable=false)
    public ChronicDisease getChronicDisease() {
        return this.chronicDisease;
    }
    
    public void setChronicDisease(ChronicDisease chronicDisease) {
        this.chronicDisease = chronicDisease;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SSN", nullable=false, insertable=false, updatable=false)
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    
    @Column(name="treatment", nullable=false, length=150)
    public String getTreatment() {
        return this.treatment;
    }
    
    public void setTreatment(String treatment) {
        this.treatment = treatment;
    }




}


