package com.modern.www._1_2_MySql_DB_entities;
// Generated May 13, 2022 7:18:24 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PatientCase generated by hbm2java
 */
@Entity
@Table(name="patient_case"
    ,catalog="smrtamb"
)
public class PatientCase  implements java.io.Serializable {


     private PatientCaseId id;
     private CaseData caseData;
     private Patient patient;

    public PatientCase() {
    }

    public PatientCase(PatientCaseId id, CaseData caseData, Patient patient) {
       this.id = id;
       this.caseData = caseData;
       this.patient = patient;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="transDate", column=@Column(name="trans_date", nullable=false, length=10) ), 
        @AttributeOverride(name="ssn", column=@Column(name="SSN", nullable=false) ), 
        @AttributeOverride(name="caseId", column=@Column(name="case_id", nullable=false) ) } )
    public PatientCaseId getId() {
        return this.id;
    }
    
    public void setId(PatientCaseId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="case_id", nullable=false, insertable=false, updatable=false)
    public CaseData getCaseData() {
        return this.caseData;
    }
    
    public void setCaseData(CaseData caseData) {
        this.caseData = caseData;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SSN", nullable=false, insertable=false, updatable=false)
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }




}


