package com.modern.www._1_2_MySql_DB_entities;
// Generated May 13, 2022 7:18:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PatientMeasurementsId generated by hbm2java
 */
@Embeddable
public class PatientMeasurementsId  implements java.io.Serializable {


     private Date measurementDate;
     private long ssn;

    public PatientMeasurementsId() {
    }

    public PatientMeasurementsId(Date measurementDate, long ssn) {
       this.measurementDate = measurementDate;
       this.ssn = ssn;
    }
   


    @Column(name="measurement_date", nullable=false, length=10)
    public Date getMeasurementDate() {
        return this.measurementDate;
    }
    
    public void setMeasurementDate(Date measurementDate) {
        this.measurementDate = measurementDate;
    }


    @Column(name="SSN", nullable=false)
    public long getSsn() {
        return this.ssn;
    }
    
    public void setSsn(long ssn) {
        this.ssn = ssn;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PatientMeasurementsId) ) return false;
		 PatientMeasurementsId castOther = ( PatientMeasurementsId ) other; 
         
		 return ( (this.getMeasurementDate()==castOther.getMeasurementDate()) || ( this.getMeasurementDate()!=null && castOther.getMeasurementDate()!=null && this.getMeasurementDate().equals(castOther.getMeasurementDate()) ) )
 && (this.getSsn()==castOther.getSsn());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMeasurementDate() == null ? 0 : this.getMeasurementDate().hashCode() );
         result = 37 * result + (int) this.getSsn();
         return result;
   }   


}


