package com.modern.www._1_2_MySql_DB_entities;
// Generated May 13, 2022 7:18:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PatientAmbulanceHospitalId generated by hbm2java
 */
@Embeddable
public class PatientAmbulanceHospitalId  implements java.io.Serializable {


     private Date transDate;
     private long pssn;
     private int carNumber;
     private int hospitalId;

    public PatientAmbulanceHospitalId() {
    }

    public PatientAmbulanceHospitalId(Date transDate, long pssn, int carNumber, int hospitalId) {
       this.transDate = transDate;
       this.pssn = pssn;
       this.carNumber = carNumber;
       this.hospitalId = hospitalId;
    }
   


    @Column(name="trans_date", nullable=false, length=10)
    public Date getTransDate() {
        return this.transDate;
    }
    
    public void setTransDate(Date transDate) {
        this.transDate = transDate;
    }


    @Column(name="PSSN", nullable=false)
    public long getPssn() {
        return this.pssn;
    }
    
    public void setPssn(long pssn) {
        this.pssn = pssn;
    }


    @Column(name="car_number", nullable=false)
    public int getCarNumber() {
        return this.carNumber;
    }
    
    public void setCarNumber(int carNumber) {
        this.carNumber = carNumber;
    }


    @Column(name="hospital_id", nullable=false)
    public int getHospitalId() {
        return this.hospitalId;
    }
    
    public void setHospitalId(int hospitalId) {
        this.hospitalId = hospitalId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PatientAmbulanceHospitalId) ) return false;
		 PatientAmbulanceHospitalId castOther = ( PatientAmbulanceHospitalId ) other; 
         
		 return ( (this.getTransDate()==castOther.getTransDate()) || ( this.getTransDate()!=null && castOther.getTransDate()!=null && this.getTransDate().equals(castOther.getTransDate()) ) )
 && (this.getPssn()==castOther.getPssn())
 && (this.getCarNumber()==castOther.getCarNumber())
 && (this.getHospitalId()==castOther.getHospitalId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTransDate() == null ? 0 : this.getTransDate().hashCode() );
         result = 37 * result + (int) this.getPssn();
         result = 37 * result + this.getCarNumber();
         result = 37 * result + this.getHospitalId();
         return result;
   }   


}


