package com.modern.www._1_2_MySql_DB_entities;
// Generated May 13, 2022 7:18:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PatientSurgeryDoctorId generated by hbm2java
 */
@Embeddable
public class PatientSurgeryDoctorId  implements java.io.Serializable {


     private Date surgeryDate;
     private long pssn;
     private int surgeryId;
     private long dssn;

    public PatientSurgeryDoctorId() {
    }

    public PatientSurgeryDoctorId(Date surgeryDate, long pssn, int surgeryId, long dssn) {
       this.surgeryDate = surgeryDate;
       this.pssn = pssn;
       this.surgeryId = surgeryId;
       this.dssn = dssn;
    }
   


    @Column(name="surgery_date", nullable=false, length=10)
    public Date getSurgeryDate() {
        return this.surgeryDate;
    }
    
    public void setSurgeryDate(Date surgeryDate) {
        this.surgeryDate = surgeryDate;
    }


    @Column(name="PSSN", nullable=false)
    public long getPssn() {
        return this.pssn;
    }
    
    public void setPssn(long pssn) {
        this.pssn = pssn;
    }


    @Column(name="surgery_id", nullable=false)
    public int getSurgeryId() {
        return this.surgeryId;
    }
    
    public void setSurgeryId(int surgeryId) {
        this.surgeryId = surgeryId;
    }


    @Column(name="DSSN", nullable=false)
    public long getDssn() {
        return this.dssn;
    }
    
    public void setDssn(long dssn) {
        this.dssn = dssn;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PatientSurgeryDoctorId) ) return false;
		 PatientSurgeryDoctorId castOther = ( PatientSurgeryDoctorId ) other; 
         
		 return ( (this.getSurgeryDate()==castOther.getSurgeryDate()) || ( this.getSurgeryDate()!=null && castOther.getSurgeryDate()!=null && this.getSurgeryDate().equals(castOther.getSurgeryDate()) ) )
 && (this.getPssn()==castOther.getPssn())
 && (this.getSurgeryId()==castOther.getSurgeryId())
 && (this.getDssn()==castOther.getDssn());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSurgeryDate() == null ? 0 : this.getSurgeryDate().hashCode() );
         result = 37 * result + (int) this.getPssn();
         result = 37 * result + this.getSurgeryId();
         result = 37 * result + (int) this.getDssn();
         return result;
   }   


}


