package com.modern.www._1_2_MySql_DB_entities;
// Generated May 13, 2022 7:18:24 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PatientMeasurements generated by hbm2java
 */
@Entity
@Table(name="patient_measurements"
    ,catalog="smrtamb"
)
public class PatientMeasurements  implements java.io.Serializable {


     private PatientMeasurementsId id;
     private Patient patient;
     private int heartRate;
     private int bodyTemperature;
     private int sugarLevel;
     private String pressureLevel;
     private int oxygenLevel;

    public PatientMeasurements() {
    }

    public PatientMeasurements(PatientMeasurementsId id, Patient patient, int heartRate, int bodyTemperature, int sugarLevel, String pressureLevel, int oxygenLevel) {
       this.id = id;
       this.patient = patient;
       this.heartRate = heartRate;
       this.bodyTemperature = bodyTemperature;
       this.sugarLevel = sugarLevel;
       this.pressureLevel = pressureLevel;
       this.oxygenLevel = oxygenLevel;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="measurementDate", column=@Column(name="measurement_date", nullable=false, length=10) ), 
        @AttributeOverride(name="ssn", column=@Column(name="SSN", nullable=false) ) } )
    public PatientMeasurementsId getId() {
        return this.id;
    }
    
    public void setId(PatientMeasurementsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SSN", nullable=false, insertable=false, updatable=false)
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    
    @Column(name="heart_rate", nullable=false)
    public int getHeartRate() {
        return this.heartRate;
    }
    
    public void setHeartRate(int heartRate) {
        this.heartRate = heartRate;
    }

    
    @Column(name="body_temperature", nullable=false)
    public int getBodyTemperature() {
        return this.bodyTemperature;
    }
    
    public void setBodyTemperature(int bodyTemperature) {
        this.bodyTemperature = bodyTemperature;
    }

    
    @Column(name="sugar_level", nullable=false)
    public int getSugarLevel() {
        return this.sugarLevel;
    }
    
    public void setSugarLevel(int sugarLevel) {
        this.sugarLevel = sugarLevel;
    }

    
    @Column(name="pressure_level", nullable=false, length=100)
    public String getPressureLevel() {
        return this.pressureLevel;
    }
    
    public void setPressureLevel(String pressureLevel) {
        this.pressureLevel = pressureLevel;
    }

    
    @Column(name="oxygen_level", nullable=false)
    public int getOxygenLevel() {
        return this.oxygenLevel;
    }
    
    public void setOxygenLevel(int oxygenLevel) {
        this.oxygenLevel = oxygenLevel;
    }




}


