package com.modern.www._1_2_MySql_DB_entities;
// Generated May 13, 2022 7:18:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Surgery generated by hbm2java
 */
@Entity
@Table(name="surgery"
    ,catalog="smrtamb"
)
public class Surgery  implements java.io.Serializable {


     private int surgeryId;
     private String surgeryName;
     private Set<PatientSurgeryDoctor> patientSurgeryDoctors = new HashSet<PatientSurgeryDoctor>(0);

    public Surgery() {
    }

	
    public Surgery(int surgeryId, String surgeryName) {
        this.surgeryId = surgeryId;
        this.surgeryName = surgeryName;
    }
    public Surgery(int surgeryId, String surgeryName, Set<PatientSurgeryDoctor> patientSurgeryDoctors) {
       this.surgeryId = surgeryId;
       this.surgeryName = surgeryName;
       this.patientSurgeryDoctors = patientSurgeryDoctors;
    }
   
     @Id 

    
    @Column(name="surgery_id", unique=true, nullable=false)
    public int getSurgeryId() {
        return this.surgeryId;
    }
    
    public void setSurgeryId(int surgeryId) {
        this.surgeryId = surgeryId;
    }

    
    @Column(name="surgery_name", nullable=false, length=150)
    public String getSurgeryName() {
        return this.surgeryName;
    }
    
    public void setSurgeryName(String surgeryName) {
        this.surgeryName = surgeryName;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="surgery")
    public Set<PatientSurgeryDoctor> getPatientSurgeryDoctors() {
        return this.patientSurgeryDoctors;
    }
    
    public void setPatientSurgeryDoctors(Set<PatientSurgeryDoctor> patientSurgeryDoctors) {
        this.patientSurgeryDoctors = patientSurgeryDoctors;
    }




}


